"""In-memory caching for scan results."""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/cache/memory.ipynb.

# %% auto #0
__all__ = ['ScanCache']

# %% ../../nbs/cache/memory.ipynb #c3d4e5f6
import time
from dataclasses import dataclass, field
from typing import List, Optional

from ..core.models import FileInfo

# %% ../../nbs/cache/memory.ipynb #eijtvr4kxpf
@dataclass
class ScanCache:
    """In-memory cache for scan results with time-based expiration."""
    duration_seconds: int = 300  # Cache duration (default 5 minutes)
    _files: List[FileInfo] = field(default_factory=list, repr=False)
    _timestamp: Optional[float] = field(default=None, repr=False)

    def is_valid(self) -> bool:  # True if cache is valid and not expired
        """Check if cache is valid and not expired."""
        if self._timestamp is None:
            return False
        return (time.time() - self._timestamp) < self.duration_seconds

    def get(self) -> Optional[List[FileInfo]]:  # Cached files or None if invalid
        """Get cached files if valid."""
        if self.is_valid():
            return self._files
        return None

    def set(
        self,
        files: List[FileInfo]  # Files to cache
    ) -> None:
        """Update cache with new files."""
        self._files = files
        self._timestamp = time.time()

    def clear(self) -> None:
        """Clear the cache."""
        self._files = []
        self._timestamp = None

    @property
    def age_seconds(self) -> Optional[float]:  # Age in seconds or None if not set
        """Get cache age in seconds."""
        if self._timestamp is None:
            return None
        return time.time() - self._timestamp

    @property
    def file_count(self) -> int:  # Number of cached files
        """Get number of cached files."""
        return len(self._files)
