# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/cjm-file-discovery',
                'doc_host': 'https://cj-mills.github.io',
                'git_url': 'https://github.com/cj-mills/cjm-file-discovery',
                'lib_path': 'cjm_file_discovery'},
  'syms': {}}
