"""Core data models for file discovery including FileInfo, FileType, and DirectoryInfo."""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/core/models.ipynb.

# %% auto #0
__all__ = ['FileType', 'FileInfo', 'DirectoryInfo']

# %% ../../nbs/core/models.ipynb #c3d4e5f6
from enum import Enum
from dataclasses import dataclass, field
from datetime import datetime
from typing import Any, Dict, Optional

from ..utils.formatting import format_file_size, format_timestamp

# %% ../../nbs/core/models.ipynb #osm31vr6pf
class FileType(str, Enum):
    """File type categories."""
    AUDIO = "audio"
    VIDEO = "video"
    IMAGE = "image"
    DOCUMENT = "document"
    CODE = "code"
    DATA = "data"        # .json, .xml, .csv, .db
    ARCHIVE = "archive"  # .zip, .tar, .gz
    OTHER = "other"

# %% ../../nbs/core/models.ipynb #y78ebxwove
@dataclass
class FileInfo:
    """Metadata for a discovered file or directory."""
    name: str              # File name with extension
    path: str              # Full path (provider-specific format)
    is_directory: bool     # True for directories
    size: Optional[int] = None              # Size in bytes
    modified: Optional[float] = None        # Last modified timestamp (Unix)
    created: Optional[float] = None         # Creation timestamp (if available)
    file_type: FileType = FileType.OTHER    # Categorized file type
    extension: Optional[str] = None         # File extension (without dot)
    mime_type: Optional[str] = None         # MIME type (if determinable)
    provider_name: str = "local"            # Source provider identifier
    metadata: Dict[str, Any] = field(default_factory=dict)  # Provider-specific extras

    @property
    def size_str(self) -> str:  # Human-readable size string
        """Human-readable size string (e.g., '15.2 MB')."""
        if self.size is None:
            return ""
        return format_file_size(self.size)

    @property
    def modified_str(self) -> str:  # Human-readable modified date
        """Human-readable modified date."""
        if self.modified is None:
            return ""
        return format_timestamp(self.modified)

# %% ../../nbs/core/models.ipynb #t52sjh4mh3l
@dataclass
class DirectoryInfo:
    """Metadata for a directory with optional computed statistics."""
    path: str                                  # Full directory path
    name: str                                  # Directory name
    item_count: Optional[int] = None           # Number of direct children
    total_size: Optional[int] = None           # Total size of contents (bytes)
    file_count: Optional[int] = None           # Number of files (recursive)
    directory_count: Optional[int] = None      # Number of subdirectories

    @property
    def total_size_str(self) -> str:  # Human-readable total size
        """Human-readable total size string."""
        if self.total_size is None:
            return ""
        return format_file_size(self.total_size)
