"""Protocol definitions for extensible file discovery providers."""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/core/protocols.ipynb.

# %% auto #0
__all__ = ['DiscoveryProvider']

# %% ../../nbs/core/protocols.ipynb #c3d4e5f6
from typing import List, Optional, Protocol, runtime_checkable

from .models import FileInfo
from .config import ScanConfig

# %% ../../nbs/core/protocols.ipynb #wlpvghyv2c
@runtime_checkable
class DiscoveryProvider(Protocol):
    """Protocol for file discovery backends."""

    @property
    def name(self) -> str:  # Unique identifier for this provider
        """Unique identifier for this provider (e.g., 'local', 's3')."""
        ...

    def scan(
        self,
        directories: List[str],  # Directories to scan
        config: ScanConfig        # Scan configuration
    ) -> List[FileInfo]:  # List of discovered files
        """Scan directories for files matching config."""
        ...

    async def scan_async(
        self,
        directories: List[str],  # Directories to scan
        config: ScanConfig        # Scan configuration
    ) -> List[FileInfo]:  # List of discovered files
        """Async scan for files."""
        ...

    def get_file_info(
        self,
        path: str  # Path to file
    ) -> Optional[FileInfo]:  # FileInfo or None if not found
        """Get metadata for a single file."""
        ...

    def supports_path(
        self,
        path: str  # Path to check
    ) -> bool:  # True if this provider can handle the path
        """Check if this provider can handle the given path."""
        ...
