"""Utility functions for formatting file sizes, timestamps, and other display values."""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/utils/formatting.ipynb.

# %% auto #0
__all__ = ['format_file_size', 'format_timestamp', 'matches_glob_patterns', 'get_mime_type']

# %% ../../nbs/utils/formatting.ipynb #c3d4e5f6
import fnmatch
import mimetypes
from datetime import datetime
from typing import List, Optional

# %% ../../nbs/utils/formatting.ipynb #mefi7rlhgq
def format_file_size(
    size_bytes: int  # Size in bytes
) -> str:  # Human-readable size string (e.g., "15.2 MB")
    """Format file size in human-readable format."""
    if size_bytes < 0:
        return "0 B"
    
    units = ["B", "KB", "MB", "GB", "TB", "PB"]
    unit_index = 0
    size = float(size_bytes)
    
    while size >= 1024 and unit_index < len(units) - 1:
        size /= 1024
        unit_index += 1
    
    if unit_index == 0:
        return f"{int(size)} {units[unit_index]}"
    return f"{size:.1f} {units[unit_index]}"

# %% ../../nbs/utils/formatting.ipynb #lge41dpi4x
def format_timestamp(
    timestamp: float  # Unix timestamp
) -> str:  # Human-readable date string
    """Format timestamp to human-readable date with relative time for recent files."""
    try:
        dt = datetime.fromtimestamp(timestamp)
        now = datetime.now()
        diff = now - dt
        
        # Relative time for recent files
        if diff.days == 0:
            if diff.seconds < 60:
                return "Just now"
            elif diff.seconds < 3600:
                minutes = diff.seconds // 60
                return f"{minutes} minute{'s' if minutes != 1 else ''} ago"
            else:
                hours = diff.seconds // 3600
                return f"{hours} hour{'s' if hours != 1 else ''} ago"
        elif diff.days == 1:
            return "Yesterday"
        elif diff.days < 7:
            return f"{diff.days} days ago"
        
        # Absolute date for older files
        if dt.year == now.year:
            return dt.strftime("%b %d")
        return dt.strftime("%b %d, %Y")
    except (ValueError, OSError):
        return "Unknown"

# %% ../../nbs/utils/formatting.ipynb #eg8yjinpvgr
def matches_glob_patterns(
    path: str,  # File path to check
    patterns: List[str]  # List of glob patterns to match against
) -> bool:  # True if path matches any pattern
    """Check if path matches any of the glob patterns."""
    if not patterns:
        return False
    
    for pattern in patterns:
        if fnmatch.fnmatch(path, pattern):
            return True
        # Also check just the filename
        if '/' in path or '\\' in path:
            filename = path.replace('\\', '/').split('/')[-1]
            if fnmatch.fnmatch(filename, pattern):
                return True
    return False

# %% ../../nbs/utils/formatting.ipynb #l719d0vxg7
def get_mime_type(
    path: str  # File path to check
) -> Optional[str]:  # MIME type string or None if unknown
    """Determine MIME type for a file based on extension."""
    mime_type, _ = mimetypes.guess_type(path)
    return mime_type
