"""Filter implementations for file discovery."""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/scanning/filters.ipynb.

# %% auto #0
__all__ = ['filter_files', 'sort_files', 'limit_files']

# %% ../../nbs/scanning/filters.ipynb #c3d4e5f6
import fnmatch
from typing import Callable, List, Optional

from ..core.models import FileInfo, FileType
from ..core.config import FilterConfig

# %% ../../nbs/scanning/filters.ipynb #kc4ejuewgo
def filter_files(
    files: List[FileInfo],      # Files to filter
    config: FilterConfig        # Filter configuration
) -> List[FileInfo]:  # Filtered files
    """Filter a list of files using FilterConfig."""
    return [f for f in files if config.matches(f)]

# %% ../../nbs/scanning/filters.ipynb #jqpbotow2ri
def sort_files(
    files: List[FileInfo],      # Files to sort
    sort_by: str = "name",      # Sort key: "name", "size", "modified", "type"
    descending: bool = False    # Sort in descending order
) -> List[FileInfo]:  # Sorted files
    """Sort a list of files by the specified key."""
    def get_sort_key(f: FileInfo):
        if sort_by == "name":
            return f.name.lower()
        elif sort_by == "size":
            return f.size if f.size is not None else 0
        elif sort_by == "modified":
            return f.modified if f.modified is not None else 0
        elif sort_by == "type":
            return f.file_type.value
        else:
            return f.name.lower()

    return sorted(files, key=get_sort_key, reverse=descending)

# %% ../../nbs/scanning/filters.ipynb #n9z6q4eyeci
def limit_files(
    files: List[FileInfo],       # Files to limit
    max_results: Optional[int]   # Maximum number of results (None = no limit)
) -> List[FileInfo]:  # Limited file list
    """Limit the number of files returned."""
    if max_results is None:
        return files
    return files[:max_results]
