"""High-level FileScanner class with caching and provider support."""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/scanning/scanner.ipynb.

# %% auto #0
__all__ = ['FileScanner']

# %% ../../nbs/scanning/scanner.ipynb #c3d4e5f6
import asyncio
from typing import Any, Dict, List, Optional

from ..core.models import FileInfo, FileType
from ..core.config import ScanConfig, ExtensionMapping
from ..cache.memory import ScanCache
from ..providers.local import LocalDiscoveryProvider
from .filters import filter_files, sort_files, limit_files
from ..utils.formatting import format_file_size

# %% ../../nbs/scanning/scanner.ipynb #ywo8daivedm
class FileScanner:
    """High-level file scanner with caching and provider support."""

    def __init__(
        self,
        config: ScanConfig,  # Scan configuration
        provider: Optional[Any] = None  # Discovery provider (defaults to LocalDiscoveryProvider)
    ):
        """Initialize the scanner."""
        self.config = config
        self.provider = provider or LocalDiscoveryProvider()
        self._cache = ScanCache(duration_seconds=config.cache_duration_seconds)

    def scan(
        self,
        force_refresh: bool = False  # Force fresh scan, ignoring cache
    ) -> List[FileInfo]:  # List of discovered files
        """Scan for files, using cache if valid."""
        # Check cache first
        if not force_refresh and self.config.cache_results:
            cached = self._cache.get()
            if cached is not None:
                return cached

        # Perform scan
        files = self.provider.scan(self.config.directories, self.config)

        # Sort results
        files = sort_files(files, self.config.sort_by, self.config.sort_descending)

        # Apply limit
        files = limit_files(files, self.config.max_results)

        # Update cache
        if self.config.cache_results:
            self._cache.set(files)

        return files

    async def scan_async(
        self,
        force_refresh: bool = False  # Force fresh scan, ignoring cache
    ) -> List[FileInfo]:  # List of discovered files
        """Async scan for files."""
        # Check cache first
        if not force_refresh and self.config.cache_results:
            cached = self._cache.get()
            if cached is not None:
                return cached

        # Perform async scan
        files = await self.provider.scan_async(self.config.directories, self.config)

        # Sort results
        files = sort_files(files, self.config.sort_by, self.config.sort_descending)

        # Apply limit
        files = limit_files(files, self.config.max_results)

        # Update cache
        if self.config.cache_results:
            self._cache.set(files)

        return files

    def get_files_by_type(
        self,
        file_types: List[FileType]  # File types to filter by
    ) -> List[FileInfo]:  # Filtered files
        """Get files filtered by specific file types."""
        files = self.scan()
        return [f for f in files if f.file_type in file_types]

    def clear_cache(self) -> None:
        """Clear the scan cache."""
        self._cache.clear()

    @property
    def cache_valid(self) -> bool:  # True if cache is valid
        """Check if cache is valid."""
        return self._cache.is_valid()

    @property
    def cached_file_count(self) -> int:  # Number of cached files
        """Get number of cached files."""
        return self._cache.file_count

    def get_summary(self) -> Dict[str, Any]:  # Summary statistics
        """Get summary statistics for scanned files."""
        files = self.scan()

        # Total stats
        total_size = sum(f.size for f in files if f.size is not None)

        # By type breakdown
        by_type: Dict[str, int] = {}
        for f in files:
            type_name = f.file_type.value
            by_type[type_name] = by_type.get(type_name, 0) + 1

        # By extension breakdown (top 10)
        by_extension: Dict[str, int] = {}
        for f in files:
            if f.extension:
                by_extension[f.extension] = by_extension.get(f.extension, 0) + 1
        # Sort by count and take top 10
        by_extension = dict(sorted(by_extension.items(), key=lambda x: x[1], reverse=True)[:10])

        return {
            'total_files': len(files),
            'total_size': total_size,
            'total_size_str': format_file_size(total_size),
            'by_type': by_type,
            'by_extension': by_extension,
            'directories': self.config.directories,
            'cache_valid': self.cache_valid
        }
